### ISSUE TITLE
Not Updated in SV1.3

### ISSUE THREAD

**Issue by AlexUnknown37** [urbanyeti/stardew-better-ranching#1]
Is this mod still being worked on? If so it would be really amazing if it updated or became open sourced.

**Comment by urbanyeti** [comment]
I'm still planning to work on the mod, but realistically, I probably won't have a fix out until next week. I'm still configuring the github page (and it's been awhile since I've done this) but if anyone wants to contribute feel free to make a pull request!

**Comment by urbanyeti** [comment]
vaindil came through and got everything working again!
