### ISSUE TITLE
Heart bubble not showing on animals

### ISSUE THREAD

**Issue by Tenebrosful** [urbanyeti/stardew-better-ranching#16]
![image](https://github.com/urbanyeti/stardew-better-ranching/assets/48710891/681d20dc-26e3-4be9-ad9f-cf1b51c9c7ca)
![image](https://github.com/urbanyeti/stardew-better-ranching/assets/48710891/2f3c578a-b00b-4c7b-a382-61ed230871fb)

(Idk if it can help but it was working with Better Ranching Updated)

https://smapi.io/log/64a3714fce05482582f884c8de07e4e4

**Comment by urbanyeti** [comment]
Hmmm... not sure what's causing this. I can see hearts appear above my animals-- do you have the Better Ranching Updated running along side the newest version? Could you try disabling it?

**Comment by Tenebrosful** [comment]
As showing in the smapi logs Better Ranching Updated isn't running, i deleted it from mods when you updated the mod, i'm gonna test few scenarios like different save, re-generate config.json but saw someone on nexus post having the same issue with 2.0.0

**Comment by Tenebrosful** [comment]
Ok updates: It seems to appear with animals that use new 1.6 feature for modding skins
![image](https://github.com/urbanyeti/stardew-better-ranching/assets/48710891/d381863b-2cdf-40e3-884c-5e9f45857339)
As you can see here animals not having modded skin (i use Ella's cutter) have them bubble but not the one with modded skins

It seems to don't affect Pets (beside they also use 1.6 modded skin)

It was working with Better Ranching Updated so it can be fix i guess

**Comment by urbanyeti** [comment]
Ooooh, interesting! Thank you so much for investigating. I think I can get a hotfix out very soon!

**Comment by Tenebrosful** [comment]
No problem, that's my occupation since 1.6 release lmao, i go mods to mods to try to update them / make translation etc

**Comment by Tenebrosful** [comment]
Don't know how your code work but probably take a look at https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6#Custom_farm_animals

**Comment by urbanyeti** [comment]
I think I was able to get this fixed and put out a new hotfix (2.0.1)-- not sure if the skins ended up being related, but please take a look and let me know if you have any issues.

**Comment by Tenebrosful** [comment]
2.0.1 working just fine as i can look !
