### ISSUE TITLE
MEEP-spawned farm animals being treated as regular farm animals

### ISSUE THREAD

**Issue by AlanDavison** [urbanyeti/stardew-better-ranching#18]
I've had a report on  MEEP that Better Ranching is (understandably) showing the pet/interaction indicators over MEEP-spawned farm animals. Which makes perfect sense, of course, since Better Ranching has no understanding of MEEP, or that MEEP even exists.

I can see a few potential solutions to this:

1) I can add an API to MEEP to return whether a given farm animal is MEEP-spawned or not, and PR that functionality into Better Ranching.

Or, which I would much rather avoid if possible...

2) I can just directly transpile your `OnRenderedWorld` method to skip over MEEP-spawned farm animals.

Let me know which of these options sound better to you. Thanks!

**Comment by urbanyeti** [comment]
I merged in your PR (https://github.com/urbanyeti/stardew-better-ranching/pull/20) which I believe should resolve this?

Closing the the issue, but let me know if I'm misunderstanding and I can re-open and address it.
