### ISSUE TITLE
Bubbles misalign if UI scale not 100%

### ISSUE THREAD

**Issue by ericthomasca** [urbanyeti/stardew-better-ranching#19]
If the UI scale is not 100%, the bubbles move to the right if over 100 and to left if under 100, making them not over the animals heads anymore. Same bug on Better Friendship, putting issue there too.

**Comment by urbanyeti** [comment]
Unfortunately this seems to be an issue with either SMAPI or SDV itself: https://github.com/Pathoschild/SMAPI/issues/936
