### ISSUE TITLE
SMAPI 3.0 updates needed

### ISSUE THREAD

**Issue by rikai** [urbanyeti/stardew-better-ranching#5]
This looks like it's actually been taken care of in the repo already with pull #4 being merged, but hasn't actually been released over on nexus yet, so I'll go ahead and open this anyway as a tracking issue.

Am getting the following errors when launching using the current stable SMAPI, and [SMAPI 3.0 is on the horizon](https://stardewvalleywiki.com/Modding:Migrate_to_SMAPI_3.0).

>[SMAPI] Better Ranching will break in the upcoming SMAPI 3.0 (legacy events are deprecated since SMAPI 2.9).

**Comment by urbanyeti** [comment]
Thanks for reminder! Updated on nexus.
