### ISSUE TITLE
Changes for SDV 1.5

### ISSUE THREAD

**Issue by corrinr** [urbanyeti/stardew-better-ranching#8]
I've made an unofficial update on the forums here: http://forums.stardewvalley.net/threads/unofficial-mod-updates.2096/post-20828 It just needs a recompile to work. There's also an issue with the hearts not being in the correct place when UI scaling is used, which the unofficial doesn't fix.

**Comment by urbanyeti** [comment]
Hey, this is fantastic! If you'd like to create a pull request I can merge the changes to the official mod. :)

**Comment by corrinr** [comment]
Since it was just a recompile there were no changes to my local clone, so I wasn't able to make a PR! I didn't make any changes for UI scaling.

**Comment by urbanyeti** [comment]
Oh, gotcha! I'm working on a fix for the UI issue right now, but in the mean time I put up a link to your post on the nexus mod page so people don't miss out. Thanks for helping out!

**Comment by corrinr** [comment]
No problem, thanks for taking a look at it!
